services:
  diagram-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - AGENT_POOL_SIZE=3
      - LOG_LEVEL=INFO
      - IMAGES_DIR=/tmp/diagram_service_images
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Live code mount for development - mount entire project
      - .:/app
      # Mount for temporary files
      - /tmp/diagram-service:/tmp/diagram-service
    command: uv run uvicorn diagram_service.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    networks:
      - diagram-network

  chainlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - IMAGES_DIR=/tmp/diagram_service_images
    env_file:
      - .env
    volumes:
      # Live code mount for development - mount entire project
      - .:/app
    command: uv run chainlit run diagram_service/chainlit_app.py --host 0.0.0.0 --port 8001 --debug
    depends_on:
      - diagram-service
    networks:
      - diagram-network

networks:
  diagram-network:
    driver: bridge
